### ISSUE TITLE
arm64 images for DockerMac (M1 Apple Silicon)

### ISSUE THREAD

**Issue by gmuth** [dockersamples/wordsmith#26]
This could be great demo for k8s on Apple Silicon!
Could you please provide arm64 builds on dockerhub?
Otherwise default kubernetes installations pull the amd64 images which don't work on M1 Macs with Docker Mac

**Comment by gmuth** [comment]
I have [patched kube-deployment.yml](https://github.com/gmuth/k8s-wordsmith-demo/commit/08cece6b543cac51fcfe2146e3fa7e5087c5d989) in order to have kubernetes use the local arm64 images instead of pulling the amd64 images.

**Comment by mikesir87** [comment]
Hi @gmuth! 👋  Thanks for the issue and apologies that it's taken so long for us to respond to you. But... we're finally looping back and cleaning up our sample apps!

We've created new image repos and manually created/pushed images that are multi-arch! 🎉 We'll soon be adding GitHub Actions that will build them automatically going forward.
