### ISSUE TITLE
Rename words folder to api

### ISSUE THREAD

**Issue by mikesir87** [dockersamples/wordsmith#40]
It feels a little odd to have the API directory to be named `words`. Instead, we should rename it to `api`. Update any GHA workflows, compose files, etc. for the change.

**Comment by BretFisher** [comment]
Fixed by #42

**Comment by thejustin** [comment]
This change causes the error `unable to prepare context: path "words" not found` after running `docker compose up --build`

I got it working locally by changing my local folder name back to "words"

**Comment by mikesir87** [comment]
Oops! Looks like we missed that config there. But hey! Good to know someone is still using the project 😂 I'll get it fixed ASAP 👍
